### ISSUE TITLE
Jupyter Wrapping Text

### ISSUE THREAD

**Issue by Hernan4444** [IIC2433-2017-2/T01#1]
Hola, 
 Intentando hacer el `print` del árbol, me percaté que jupyter hace wrap de los `print`, es decir, si el texto a imprimir supera un largo determinado, lo continua en la linea de abajo. Esto enlo personal me dificulta la impresion de un árbol con sus hojas cuando este tiene una altura demasiado alta.

A continuación se ve un árbol según los print que hice.
![image](https://user-images.githubusercontent.com/15641721/30383408-fb6fdd2c-9877-11e7-9d9a-c4b33d250112.png)

Pero cuando es hora de imprimir un árbol de grán altura, este queda así:

![image](https://user-images.githubusercontent.com/15641721/30383485-2ed2edf8-9878-11e7-9c35-c98b1bcb0fd8.png)

Estaba pensando en buscar otra forma de visualizar el árbol pero antes quería saber si conocen una forma de deshabilitar ese wrapping de jupyter porque al menos cuando uno visualiza una tabla de Pandas, en esta se genera un horizontal scroll bar, pero busque en Google y no logré encontrar como alterar esa funcionalidad.

Muchas gracias de antemano
Saludos ✌️

**Comment by NevadaStreets** [comment]
Hola!

Tienes dos opciones:
1.- Puedes probar con la función `display` en vez de `print`.
2.- Pueden guardar el resultado en un archivo `.txt`, de esta forma no tendrás el problema de las celdas en `jupyter`.

Creo que recomiendo la segunda, porque siempre puede crecer mucho el árbol. En términos de escalabilidad, guardarlo en un archivo es la mejor opción.

Saludos!

**Comment by Geeermy** [comment]
¡Hola!

Colándome un poco en este issue, ¿está bien si me basé en lo que salía en los apuntes de estructuras en Python para formar el árbol? (modificando su representación y mostrando cada conexión entre nodos en una fila solamente, ahí mismo añadí los labels y los contadores) ¿o debería modificarla?

¡Gracias! :^)

**Comment by NevadaStreets** [comment]
Está permitido basarse en esos apuntes, aunque puede que no sea la estructura óptima.

Y no entiendo la visualización que acabas de explicar. Debe quedar en claro la forma del árbol al visualizarlo. Se debe poder ver todo, sus nodos, conexiones, labels y atributos de forma clara.

Saludos!
