### ISSUE TITLE
Resultado de prueba

### ISSUE THREAD

**Issue by Hernan4444** [IIC2433-2017-2/T01#12]
Hola,
 Sé que es mucho pedir, pero será posible subir el resultado de aplicar FP-Growth a los csv entregados (acciones y votaciones) con alguna confianza y soporte que ustedes indiquen, así podríamos testear si al menos estamos encontrando los mismos itemset frecuentes con el soporte esperado. A pesar de que tenemos el ejemplo de clases, este tiene muy pocos ítems como para testear toda la funcionalidad de algoritmo.

Gracias de antemano
ps: En caso de no ser posible, ¿nos permitirían subir por aquí el resultado de algunas aplicaciones y así comparar entre varios si llegamos a lo mismo?

**Comment by bcsaldias** [comment]
Hola,

La imagen del enunciado es suficientemente representativa. Si pueden
subirlas y comparar.

Saludos!
