### ISSUE TITLE
Duda podas post sumar por nivel

### ISSUE THREAD

**Issue by rmant** [IIC2433-2017-2/T01#13]
Una pregunta! 

Una vez que ya tengo construido el arbol con la suma por nivel, con sus respectivos contadores de soporte totales en cada nodo, bajo que criterio puedo podar un arbol? Si su soporte sumado es menor que el soporte dado puedo cortarlo?

Me acuerdo que en clases se mencionó un caso borde en el que si no me equivoco, no se podia llegar y cortar.

Muchas gracias!

**Comment by bcsaldias** [comment]
Hola!

Es por ejemplo cuando un nodo queda con menor soporte del debido. Pero si
cuentas ese nodo en todas sus apariciones es mayor que el soporte, por lo
que no hay que podarlo.

Creo que el ejemplo de clases lo mostraba en los caminos a I3

Saludos!
