### ISSUE TITLE
Duda con respecto al enunciado sobre los decimales para comparar

### ISSUE THREAD

**Issue by Geeermy** [IIC2433-2017-2/T01#14]
¡Hola! Me vino la duda con esta sentencia:

> “path_ input”_rules.csv: Si bien las métricas se deben analizar con al menos 2 dígitos de significancia, para esta tarea solo se comparará el primer decimal (truncado) para evaluar la exactitud de la implementación. Sin embargo, procure exportar las reglas con 2 decimales. La siguiente figura muestra.

¿Esto qué significa? ¿Que para hacer el filtro por confianza comparo los valores truncados a un decimal? ¿También aplica para los soportes? Hasta ahora estaba haciendo todo con todos los decimales y, como solo me falta hacer el informe, me gustaría arreglar eso antes de comenzar el análisis...

¡De antemano gracias! :)

**Comment by bcsaldias** [comment]
El análisis con 2.
La nota será puesta según exactotud a 1 decimal truncado.

**Comment by Geeermy** [comment]
¡Perfecto! Muuuchas gracias c:
