### ISSUE TITLE
Sobre los archivos

### ISSUE THREAD

**Issue by Geeermy** [IIC2433-2017-2/T01#4]
¡Hola!

Mientras probaba algunos métodos sobre mis archivos, me di cuenta que algunos tienen líneas vacías (por ejemplo, para votaciones.csv la línea 151 no es más que otro salto de línea...).

¿El programa debería manejar dichos casos o simplemente lo asumo como error de formato y lo arreglo manualmente?

¡Gracias!

**Comment by bcsaldias** [comment]
Se puede considerar como una transacción vacía. Tampo se suma al soporte.

Podrías poner que si hay al menos un item en la línea la cuente como
transacción. Pero el input no debería ser así. Debería ser cada línea una
transacción.
