### ISSUE TITLE
Descuento por commits

### ISSUE THREAD

**Issue by Geeermy** [IIC2433-2017-2/T01#5]
¡Hola!

Perdón por tantas issues jaja. Quería saber qué tan estricto es el tema de los commits. Esto ya que, por ejemplo, algunas partes del algoritmo se me es más fácil implementarlas juntas que separadas (en particular, el filtrado y orden de ítemsets).

Entiendo que lo que se busca es que se realicen commits constantemente, pero ¿habrá problema si ciertas partes las implemento juntas? Es más que todo para poder facilitar lo que voy completando y que compute más rápido.

¡Gracias!

**Comment by bcsaldias** [comment]
Hola,

Los commits no deberían tener que ver con el cómputo, porque es solo para
versionamiento de código y revisión.

Sin embargo, si crees que te acomoda otra granularidad puedes juntar esas
dos funciones. Con el resto hay que ser consistente o preguntar.

Saludos!
