### ISSUE TITLE
Librerías permitidas

### ISSUE THREAD

**Issue by jgmontoya** [IIC2433-2017-2/T01#6]
Abro esta issue para preguntar sobre librerías en general para la tarea. La idea es que si alguien más quiere saber sobre si es legal usar cierta librería o no lo pueda preguntar en esta misma issue y así mantenemos una lista actualizada.

## Librerías legales por enunciado:
  * numpy
  * pandas
  * matplotlib

## Librerías aceptadas (teniendo ojo :eye: )
  * itertools
  * collections
> Con respecto a esos paquetes: pueden utilizarlos siempre y cuando NO
interfieran los pasos del algoritmo.

## Nota:
Para el bonus 6.1 y 6.2, correspondiente a visualización de FP-Tree y visualización de reglas de asociación respectivamente se ha autorizado a priori cualquier librería (ver #2). Incluso se autorizó a hacer el punto 6.2 en otros lenguajes.

**Comment by jgmontoya** [comment]
¿Se puede usar [itertools](https://docs.python.org/3/library/itertools.html)?

**Comment by Geeermy** [comment]
Ojo que, al menos para el bonus 6.2, incluso se puede programar en otro lenguaje (según enunciado). Me tinca que para hacer algo más interactivo sería útil considerar otras posibilidades :^).

Con respecto a itertools y collections, me parece que Belén dijo en clases explícitamente que no se podían utilizar (ya que facilitaban muchas cosas). En lo que esperamos a que responda esta issue confirmándolo, te recomendaría avanzar asumiendo que no se puede jeje.

**Comment by jgmontoya** [comment]
> Ojo que, al menos para el bonus 6.2, incluso se puede programar en otro lenguaje (según enunciado). Me tinca que para hacer algo más interactivo sería útil considerar otras posibilidades :^).

Buena acotación, lo agregaré a la nota

> Con respecto a itertools y collections, me parece que Belén dijo en clases explícitamente que no se podían utilizar (ya que facilitaban muchas cosas). 

No recuerdo que haya dicho eso de itertools, de todas formas es mejor esperar a que Belén o algún ayudante lo confirme/niegue.

**Comment by bcsaldias** [comment]
Hola,

Con respecto a esos paquetes: pueden utilizarlos siempre y cuando NO
interfieran los pasos del algoritmo.

Semestres anteriores alumnos usan ese paquete y como tiene tantas
funcionalidades de conjuntos, olvidan por qué el algoritmo no usa esas
técnicas (eficiencia principalmente - principios del algoritmo, al final se
presenta una forma eficiente de encontrar los itemsets frecuentes).

Si quieren usarlo para crear las reglas una vez que ya tienen todos los
itemsets podría ser. Siempre y cuando no pasen por alto por qué el
algoritmo es como es.

Recuerden que después tomo cada itemset frecuente y veo sus subconjuntos y
complementos. Tal vez en esta parte su implementación sea tan eficiente
como el itertools (así que pueden usarlo específicamente para esto), en
otro caso, no convendría usarlo.

En cuanto a collection, ¿no se puede solucionar con Pandas lo que deseas
hacer?

Espero haber sido clara.

Como tip para autorevisión, recuerden que si un itemset es frecuente,
cualquier combinación que es subconjunto también es frecuente. Esto puede
ayudarlos mucho en el cálculo del soporte.

Saludos!

**Comment by jgmontoya** [comment]
Quiero usar itertools para generar las distintas combinaciones a partir de un iterable de forma eficiente. Me imagino que esto cabe dentro del uso permitido o no?

**Comment by jgmontoya** [comment]
¿Puedo usar [pprint](https://docs.python.org/3/library/pprint.html)?

Lo quiero ocupar para que, al usar el programa en modo 'verboso' imprimir diccionarios/listas/etc.. en un formato más legible.

Saludos!

**Comment by rmant** [comment]
Puedo utilizar itertools para calcular el conjunto potencia de un set?

**Comment by bcsaldias** [comment]
De qué set?

**Comment by rmant** [comment]
Luego de generar la suma por niveles al buscar itemset frecuentes, tengo los respectivos candidatos a combinarse con mi item, y sus soportes. 

Puedo utilizar itertools para encontrar el conjunto potencia de este conjunto, y luego combinarlo con el item buscado? No sé si se entendió el caso.
