### ISSUE TITLE
Interpretación orderby

### ISSUE THREAD

**Issue by Hernan4444** [IIC2433-2017-2/T01#7]
Hola,
En el enunciado dice: 
> integer: orderby (soporte o contador, confianza o lift). Indica el orden de las reglas en el output
Como diferenciamos si queremos ordenar por confianza o por lift? 

Me gustaría saber bien a que se refiere con que *orderby* es tipo `integer`. Entiendo que este input es para ordenar por soporte/contador o por confianza/lift pero si es un tipo integer tengo que interpretar como (ejemplos):
1. **0**: Ordenar por soporte o contador
1. **1**: Odenar por confianza o lift

lo interpreto como:
1. `orderby == soporte/contador`: Ordenar por soporte o contador
1. `orderby == confianza`: Ordenar por confianza o lift

¿Queda a mi criterio como interpretarlo? o ¿no era un `integer` sino un `string` que podía ser: *lift*, *confianza* o *soporte*?

Muchas gracias de antemano
Saludos!

**Comment by bcsaldias** [comment]
Hola,

Decídelo tú :). La idea es poder ordenar por cualquiera de las 3 métricas
den enunciado: soporte, confianza, lift. Esto más que un requerimiento de
evaluación en si, es para que el output sea de mucha utilidad para el que
quiera usar el modelo.

Saludos!
